import React, { useRef } from 'react'

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <div style={{
        fontSize: 10, fontWeight: 700, textTransform: 'uppercase',
        letterSpacing: '0.1em', color: 'var(--accent)', marginBottom: 10,
        display: 'flex', alignItems: 'center', gap: 8
      }}>
        <div style={{ flex: 1, height: 1, background: 'var(--border)' }} />
        {title}
        <div style={{ flex: 1, height: 1, background: 'var(--border)' }} />
      </div>
      {children}
    </div>
  )
}

export default function ExecutiveReport({ report, incident }) {
  const printRef = useRef(null)

  if (!report) {
    return (
      <div style={{
        display: 'flex', flexDirection: 'column', alignItems: 'center',
        justifyContent: 'center', height: '100%', gap: 16, color: 'var(--text2)'
      }}>
        <div style={{ fontSize: 40 }}>📊</div>
        <div style={{ fontSize: 14, fontWeight: 600 }}>Executive Report</div>
        <div style={{ fontSize: 12, maxWidth: 240, textAlign: 'center', lineHeight: 1.6 }}>
          Complete the investigation to generate a board-ready incident report
        </div>
      </div>
    )
  }

  const sevColor = report.severity === 'CRITICAL' ? '#ef4444' :
                   report.severity === 'HIGH' ? '#f97316' :
                   report.severity === 'MEDIUM' ? '#f59e0b' : '#10b981'

  return (
    <div ref={printRef} style={{ padding: '24px', overflowY: 'auto', height: '100%', fontSize: 13 }}>
      {/* Header */}
      <div style={{
        background: 'linear-gradient(135deg, var(--bg3), var(--bg2))',
        border: '1px solid var(--border)', borderRadius: 12,
        padding: '20px 24px', marginBottom: 24,
        borderTop: `3px solid ${sevColor}`
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <div style={{ fontSize: 10, color: 'var(--text2)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 6 }}>
              CONFIDENTIAL — INCIDENT REPORT
            </div>
            <div style={{ fontWeight: 800, fontSize: 20, letterSpacing: '-0.02em', marginBottom: 6 }}>
              {report.incident_title || incident?.title}
            </div>
            <div style={{ color: 'var(--text2)', fontSize: 12 }}>
              Generated by CyberGuard AI • {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </div>
          </div>
          <div style={{ textAlign: 'center' }}>
            <span className={`badge badge-${report.severity?.toLowerCase()}`} style={{ fontSize: 12, padding: '6px 14px' }}>
              {report.severity}
            </span>
            {report.risk_metrics && (
              <div style={{
                marginTop: 8, fontFamily: 'var(--mono)',
                fontSize: 24, fontWeight: 800, color: sevColor
              }}>
                {report.risk_metrics.overall_risk}<span style={{ fontSize: 12, color: 'var(--text2)' }}>/100</span>
              </div>
            )}
          </div>
        </div>

        {/* Key facts */}
        {report.key_facts && (
          <div style={{
            display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
            gap: 12, marginTop: 16, paddingTop: 16, borderTop: '1px solid var(--border)'
          }}>
            {report.key_facts.slice(0, 6).map((f, i) => (
              <div key={i}>
                <div style={{ fontSize: 10, color: 'var(--text2)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 2 }}>{f.label}</div>
                <div style={{ fontWeight: 700, fontSize: 13, fontFamily: 'var(--mono)' }}>{f.value}</div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Executive Summary */}
      <Section title="Executive Summary">
        <div style={{
          color: 'var(--text1)', lineHeight: 1.8, fontSize: 14,
          background: 'var(--bg3)', borderRadius: 8, padding: '16px 20px',
          border: '1px solid var(--border)'
        }}>
          {report.executive_summary}
        </div>
      </Section>

      {/* What happened / impact / response */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 28 }}>
        {[
          { label: 'What Happened', icon: '🔍', content: report.what_happened, color: '#3b82f6' },
          { label: 'Business Impact', icon: '💼', content: report.business_impact, color: '#ef4444' },
          { label: 'Our Response', icon: '🛡️', content: report.what_we_did, color: '#10b981' },
          { label: 'Next Steps', icon: '🎯', content: report.what_happens_next, color: '#8b5cf6' },
        ].map((s, i) => (
          <div key={i} className="card" style={{ borderLeft: `3px solid ${s.color}` }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
              <span>{s.icon}</span>
              <span style={{ fontWeight: 700, fontSize: 12, color: s.color, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{s.label}</span>
            </div>
            <div style={{ color: 'var(--text1)', lineHeight: 1.7, fontSize: 13 }}>{s.content}</div>
          </div>
        ))}
      </div>

      {/* Incident Timeline */}
      {report.timeline?.length > 0 && (
        <Section title="Incident Timeline">
          <div style={{ position: 'relative', paddingLeft: 24 }}>
            <div style={{
              position: 'absolute', left: 7, top: 8, bottom: 8,
              width: 2, background: 'var(--border)'
            }} />
            {report.timeline.map((event, i) => (
              <div key={i} style={{ position: 'relative', marginBottom: 16 }}>
                <div style={{
                  position: 'absolute', left: -20, top: 4,
                  width: 10, height: 10, borderRadius: '50%',
                  background: i === 0 ? '#ef4444' : i === report.timeline.length - 1 ? '#10b981' : 'var(--bg4)',
                  border: `2px solid ${i === 0 ? '#ef4444' : i === report.timeline.length - 1 ? '#10b981' : 'var(--border2)'}`,
                }} />
                <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                  <span style={{
                    fontFamily: 'var(--mono)', fontSize: 11, color: 'var(--accent)',
                    whiteSpace: 'nowrap', marginTop: 1, minWidth: 100
                  }}>{event.time}</span>
                  <div>
                    <div style={{ fontWeight: 600, fontSize: 13 }}>{event.event}</div>
                    {event.significance && (
                      <div style={{ fontSize: 11, color: 'var(--text2)', marginTop: 2 }}>{event.significance}</div>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Recommendations */}
      {report.recommendations?.length > 0 && (
        <Section title="Recommendations">
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {report.recommendations.map((rec, i) => {
              const priColor = rec.priority === 'Immediate' ? '#ef4444' :
                               rec.priority === 'Short-term' ? '#f59e0b' : '#3b82f6'
              return (
                <div key={i} style={{
                  display: 'flex', gap: 12, alignItems: 'flex-start',
                  padding: '10px 14px', borderRadius: 8,
                  background: 'var(--bg3)', border: '1px solid var(--border)'
                }}>
                  <span style={{
                    fontSize: 10, fontWeight: 700, padding: '3px 8px',
                    borderRadius: 10, background: `${priColor}15`,
                    color: priColor, border: `1px solid ${priColor}30`,
                    textTransform: 'uppercase', letterSpacing: '0.05em',
                    whiteSpace: 'nowrap', flexShrink: 0, marginTop: 1
                  }}>{rec.priority}</span>
                  <div>
                    <div style={{ fontWeight: 600, fontSize: 13 }}>{rec.action}</div>
                    {rec.rationale && <div style={{ fontSize: 11, color: 'var(--text2)', marginTop: 3 }}>{rec.rationale}</div>}
                  </div>
                </div>
              )
            })}
          </div>
        </Section>
      )}

      {/* Lessons Learned */}
      {report.lessons_learned?.length > 0 && (
        <Section title="Lessons Learned">
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {report.lessons_learned.map((lesson, i) => (
              <div key={i} style={{
                display: 'flex', gap: 10, alignItems: 'flex-start',
                color: 'var(--text1)', fontSize: 13, lineHeight: 1.6
              }}>
                <span style={{ color: 'var(--accent)', fontWeight: 700, flexShrink: 0 }}>→</span>
                {lesson}
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Footer */}
      <div style={{
        borderTop: '1px solid var(--border)', paddingTop: 16, marginTop: 8,
        display: 'flex', justifyContent: 'space-between',
        color: 'var(--text2)', fontSize: 11, fontFamily: 'var(--mono)'
      }}>
        <span>CyberGuard AI — Powered by Band of Agents</span>
        <span>CONFIDENTIAL — NOT FOR DISTRIBUTION</span>
      </div>
    </div>
  )
}
